sql-connection:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: ''
  database: 'reputationplus'
options:
  #                                     | PLACEHOLDERS |
  # Player placeholders: %rep_player% - display name of the player that have executed the command
  #                      %rep_player_reputation% - reputation of the player
  #                      %rep_player_votes% - how many votes has the player given to another players
  #
  # Target placeholders: same ones, just replace player with target in each placeholder
  #
  # Time placeholders: %rep_time_until% - time until player is able to rate again
  #                    %rep_time_ago% - when did a player rate target from now
  #
  # Other placeholders | works only on locations they are on and do not support PlaceholderAPI:
  #                                                           %rep_reason% - reason for voting
  #                                                           %rep_decision% - returns either +rep or -rep
  #
  # From update 3.1 you can use multiple placeholders in one message such as:
  #                           %rep_target% was rated by &rep_player&! Now %rep_target% has %rep_target_reputation&!
  # Perfect scenario for this plugin would be just translating the messages or changing the colors


  # limit of how many votes can one player give to another one no matter if he chose +rep or -rep
  # example:
  #   player1 rates player2 'maxVotes' times and cannot vote for him anymore, but he can vote for other players
  maxVotes: 10
  # sends player this message if the player has reached maximum votes set by maxVotes
  maxVotes-message: '&cYou have reached the maximum amount of votes &6%rep_target%&c!'

  # set to false if you want to disable prefix in front of every message
  use-prefix: true
  prefix: '&8[&bReputation&3+&8]'

  # set to true if you want to let players vote for themselves
  can-self-vote: false
  # this message will display if can-self-vote is false
  no-self-vote-message: "&cYou can't vote for yourself!"

  rep-command:
    # set to true if you want to make players only vote +rep. This will disable any GUI related features
    plus-rep-only: false
    # use prefix in front of each message in rep-command-messages
    use-prefix: true
    # messages that will be sent to the player by '/rep' command
    messages:
      - '&aYour reputation: &b%rep_player_reputation%'
      - '&aYour votes: &b%rep_player_votes%'

  reptop-command:
    # maximum number of players shown
    limit: 5
    # message if there are no players in the database thus no one can be shown
    no-players-found: '&cNo players found!'
    # you can use {position}, {name} and {reputation} placeholders in this message
    format:
      - "&bTop Rated Players:"
      # please use message below always as the last one
      - "&3{position}: &b{name} &3- &b{reputation}"

  # interval in which are players allowed to rate another player
  interval-options:
    # if you want to manage command interval by different plugin, you can disable this interval
    enabled: true
    # valid options: s (seconds), m (minutes), h (hours), d (days)
    # do not use something like 1d5h rather use 29h
    interval: '1d'
    # this message will display if player is not allowed to rate another player yet
    message: '&cYou need to wait &6%rep_time_until%&c before you can rate again!'

  gui-options:
    # ONLY TARGET PLACEHOLDERS ARE VIABLE || DO NOT USE PLAYER PLACEHOLDERS
    # the way this plugin is coded allows GUI to gather only target placeholders!!

    # sets the title of GUI after /rep <player>
    title: '&bReputation of &3%rep_target%'

    # set this to false if you don't want to use reasons
    enable-reasons: true

    # this option changes the look of rep GUI. Shows 7 latest voters and their ratings on the target
    show-latest-voters:
      enabled: true
      # this is a sign that shows under a target player head in GUI. You can set it's title here
      sign-title: '&bLatest votes on &3%rep_target%'
      # how you would want latest voters head to look
      voter-head:
        # rep_decision will handle color depending on whenever target has been voted +rep (green) or -rep (red)
        title: '&6%rep_player% &7voted %rep_decision%'
        description:
          - '&6Reason: &e%rep_reason%'
          - '&6Voted: &e%rep_time_ago%'

    target-head:
      # color of the name of the target in GUI
      name-color: '&3'
      # sets lore of the head
      description:
        - '&3Reputation: &a%rep_target_reputation%'
        - '&3Votes: &a%rep_target_votes%'
      # - null // you can use null if you don't want description

    # set options for +rep button
    +rep-button:
      block: GREEN_TERRACOTTA
      title: '&a+rep'
      description:
        - '&3Click to &aadd &31 reputation to &b%rep_target%'

    # set options for -rep button
    -rep-button:
      block: RED_TERRACOTTA
      title: '&c-rep'
      description:
        - '&3Click to &cremove &31 reputation from &b%rep_target%'
    # set options for remaining slots of GUI, use null for empty slots
    filler:
      block: RED_STAINED_GLASS_PANE

    reason-gui-options:
      # title of +rep reason gui. Please to not make these titles equal
      positive-title: '&aSelect a positive reason'
      negative-title: '&cSelect a negative reason'

      # reasons when a player selects +rep
      +rep-reasons:
        help:
          name: '&aHelped me'
          # you can look for every material name here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
          material: DIAMOND
          description:
            - '&8%rep_target% really helped me out!'

        gave:
          name: '&aGived me items'
          material: GOLD_INGOT
          description:
            - '&8%rep_target% gived me some items!'

        kind:
          name: '&aKind to me'
          material: BOOK
          description:
            - '&8%rep_target% was very kind to me!'

        # you can add custom reasons here, please keep max reasons to 7
        # anything:
        #   name: '&aGive me a name!'
        #   material: DIAMOND_HOE
        #   description:
        #     - '&8%rep_target% is super nice!'

      -rep-reasons:
        grief:
          name: '&cGriefing'
          material: DIAMOND_PICKAXE
          description:
            - '&8%rep_target% griefed!'
        kill:
          name: '&cKilling'
          material: DIAMOND_SWORD
          description:
            - '&8%rep_target% is killing for no reason!'
        scam:
          name: '&cScammer'
          material: ENDER_EYE
          description:
            - '&8%rep_target% scammed me!'
      # entry with 'custom-reason' will always be displayed at the end of the GUI. You cannot remove this
      custom-reason:
        title: '&6Custom reason'
        material: NAME_TAG
        description:
          - '&8Choose your own reason'

messages:
  # sends player this message if he upvoted another player. Message has hover effect
  +rep-message: '&aYou have voted for &b%rep_target%&a!'
  # sets hover message, type null to disable
  +rep-hover-message: "&b%rep_target%&a's reputation is now &b%rep_target_reputation%"

  # sends player this message if he downvoted another player. Message has hover effect
  -rep-message: '&aYou have downvoted &b%rep_target%&a!'
  -rep-hover-message: "&b%rep_target%&a's reputation is now &b%rep_target_reputation%"

  # after receiving positive vote from a player, the target will be notified with this message (if he is online). Message has hover effect
  +rep-message-target: '&aYou have recieved a positive vote from &b%rep_player%!'
  +rep-hover-message-target: '&aYour reputation is now &b%rep_target_reputation%'

  # sends player this message if the player wanted to rate a player that haven't joined the server once
  player-never-seen: '&cPlayer &6%rep_target% &chas never played on this server before!'

  # sends player this message if the player does not have permission to use certain command
  no-permission: "&cYou don't have permission to use this command!"

  # sends player this message if the player reloads the config
  config-reload: "&aConfig has been reloaded!"